// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zorgboerderij.Entities;

#nullable disable

namespace Zorgboerderij.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241210081526_Bakjes")]
    partial class Bakjes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zorgboerderij.Entities.Afmeldingen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dokter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpKarwei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tandarts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vakantie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verjaardag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrij")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ziek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("afmeldingen");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.Bakjes", b =>
                {
                    b.Property<int>("bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bid"));

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bid");

                    b.ToTable("bakjes");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.Bezettingen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dinsdag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Donderdag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maandag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Totaal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrijdag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Woensdag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zaterdag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bezettingen");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.Clienten", b =>
                {
                    b.Property<int>("persid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("persid"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");



                    b.Property<int>("Dinsdag")
                        .HasColumnType("int");

                    b.Property<int>("Donderdag")
                        .HasColumnType("int");

                    b.Property<string>("FotoFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groepskleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Maandag")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vrijdag")
                        .HasColumnType("int");

                    b.Property<int>("Woensdag")
                        .HasColumnType("int");

                    b.Property<int>("Zaterdag")
                        .HasColumnType("int");

                    b.HasKey("persid");

                    b.ToTable("clienten");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.Dagcodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DagCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dagCodes");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.Personeel", b =>
                {
                    b.Property<int>("persid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("persid"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dinsdag")
                        .HasColumnType("int");

                    b.Property<int>("Donderdag")
                        .HasColumnType("int");

                    b.Property<string>("FotoFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groepskleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Maandag")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vrijdag")
                        .HasColumnType("int");

                    b.Property<int>("Woensdag")
                        .HasColumnType("int");

                    b.Property<int>("Zaterdag")
                        .HasColumnType("int");

                    b.HasKey("persid");

                    b.ToTable("personeel");
                });

            modelBuilder.Entity("Zorgboerderij.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Gebruikersnaam")
                        .IsUnique();

                    b.ToTable("userAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
